// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHTVFW6x8LNgoG7YPVtEhoSi7uNLXYB6E',
    appId: '1:730264772577:web:8aeb2999e41466ddf27ca0',
    messagingSenderId: '730264772577',
    projectId: 'flash-chat-93539',
    authDomain: 'flash-chat-93539.firebaseapp.com',
    storageBucket: 'flash-chat-93539.appspot.com',
    measurementId: 'G-VFFM9CMZZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmqSqe2uaAf3sbXG7Q1Z6wOBUPMEK-yzA',
    appId: '1:730264772577:android:7f767ed3f66bdbb9f27ca0',
    messagingSenderId: '730264772577',
    projectId: 'flash-chat-93539',
    storageBucket: 'flash-chat-93539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQFFDiN_c0rzzwjgw49IkQduPK-HLSUbk',
    appId: '1:730264772577:ios:449fb113f979e3dcf27ca0',
    messagingSenderId: '730264772577',
    projectId: 'flash-chat-93539',
    storageBucket: 'flash-chat-93539.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQFFDiN_c0rzzwjgw49IkQduPK-HLSUbk',
    appId: '1:730264772577:ios:449fb113f979e3dcf27ca0',
    messagingSenderId: '730264772577',
    projectId: 'flash-chat-93539',
    storageBucket: 'flash-chat-93539.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHTVFW6x8LNgoG7YPVtEhoSi7uNLXYB6E',
    appId: '1:730264772577:web:04582111a33e3a3cf27ca0',
    messagingSenderId: '730264772577',
    projectId: 'flash-chat-93539',
    authDomain: 'flash-chat-93539.firebaseapp.com',
    storageBucket: 'flash-chat-93539.appspot.com',
    measurementId: 'G-8SJM0BNX0V',
  );
}
